import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

const open = Open_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${open.className} flex flex-col min-h-screen`}>
        <Header />
        <div className="">
          <main className="max-w-7xl">{children}</main>
        </div>
      </body>
    </html>
  );
}
